language: android

jdk:
 - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-27.0.0
    # The SDK version used to compile your project
    - android-27

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/