pipeline {
    agent { dockerfile true }
    environment {

        GIT_HUB_USER = credentials('GitHubUser')
        GIT_HUB_TOKEN = credentials('GitHubToken')

    }
    stages {

        stage('Build exoplayer') {

            steps {
                echo 'Building ExoPlayer'
                dir('exoplayer') {
                    sh('bash ./buildffmpegext.sh all')
                }



                sh('git remote set-url origin https://${GIT_HUB_TOKEN}@github.com/OpenSageTV/sagetv-miniclient.git')
                sh('git config --global user.email "jvl711@gmail.com"')
                sh('git config --global user.name "Joshua Lewis"')

                sh('git add -A')
                sh('git commit -a -m \"Automated commit from Jenkins build fro FFmpeg extention\"')
                sh('git push origin HEAD:exoplayer')

            }

        }
    }
}