pipeline {
    agent { dockerfile true }
    environment {

        GIT_HUB_USER = credentials('GitHubUser')
        GIT_HUB_TOKEN = credentials('GitHubToken')

    }
    stages {

        stage('Build exoplayer') {

            steps {
                echo 'Building ExoPlayer'
                dir('exoplayer') {
                    sh('bash ./buildffmpegext.sh all')
                }
                sh('git remote set-url origin https://${GIT_HUB_USER}:${GIT_HUB_TOKEN}@https://github.com/OpenSageTV/sagetv-miniclient.git')
                sh('git commit -a -m \"Automated commit from Jenkins build fro FFmpeg extention\"')
                sh('git push')

            }

        }
    }
}